[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"  # or whatever version you're using

# Remove any Go-related configurations since your project doesn't need Go
