[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "http://150.136.163.34:5000/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
