[build]
  base = "frontend"
  command = "npm install && CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "http://150.136.163.34:8000/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Origin = "https://kryptostrading.com"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Authorization, Content-Type, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "3600"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
