[build]
  base = "frontend"
  command = """
    npm install --save-dev @babel/plugin-proposal-private-property-in-object &&
    CI=false npm run build
  """
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "development"

[[redirects]]
  from = "/api/ws"
  to = "http://150.136.163.34:8000/api/ws"
  status = 101
  force = true
  [redirects.headers]
    X-From = "Netlify"
    Connection = "Upgrade"
    Upgrade = "websocket"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/api/*"
  to = "http://150.136.163.34:8000/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, PATCH, DELETE"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
