[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# API proxy redirect (must come before the SPA redirect)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-domain.com/api/:splat"
  status = 200
  force = true
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Origin, Authorization, Content-Type"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
