[build]
  base = "frontend"
  command = "npm install && CI=false npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "http://150.136.163.34:8000/api/:splat"
  status = 200
  force = true
  
  [redirects.headers]
    X-Forwarded-Host = "kryptostrading.com"
    X-Forwarded-Proto = "https"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Credentials = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
